ALTER TABLE project_tags ADD COLUMN IF NOT EXISTS color TEXT DEFAULT '#6b7280';
ALTER TABLE project_tags ADD COLUMN IF NOT EXISTS group_name TEXT;
ALTER TABLE project_tags ADD COLUMN IF NOT EXISTS description TEXT;
