ALTER TABLE issues ADD COLUMN IF NOT EXISTS archived BOOLEAN DEFAULT false;
ALTER TABLE issues ADD COLUMN IF NOT EXISTS archived_at TIMESTAMPTZ;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS auto_close_days INT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS auto_archive_days INT DEFAULT 30;
